### ISSUE TITLE
Repo is defunct after removal of legacy MATLAB toolbox

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera-macos-pkg#3]
Based on my current understanding, the purpose of this repo is to package the 'traditional' MATLAB toolbox for macOS. After Cantera/cantera#1670 removed this toolbox, there is no longer a need for this workflow.

**Comment by bryanwweber** [comment]
I think this will still be needed with the new package? Maybe we should disable it until the new one is ready. Does this run in the post merge tests?

**Comment by ischoegl** [comment]
Not on post merge itself, but there's a workflow in `packaging.yml` ("Trigger macOS Package Builds")

I am overall not sure about the future of this package. Disabling it for the moment is :+1: as for all practical purposes there seems to be little use for it at the moment (we just removed the package from install instructions, and recommend sticking with Cantera 3.0 for those who depend on it).

**Comment by bryanwweber** [comment]
@ischoegl I removed the lines from the `packaging.yml` file. Otherwise, I think we should leave this repo as-is and update it when the new Matlab package is ready.

**Comment by speth** [comment]
An update to the README in this repo might be useful as well, to document the current status.

**Comment by bryanwweber** [comment]
Good idea @speth see https://github.com/Cantera/cantera-macos-pkg/commit/844314c9897edf3c70eddf3afc439ca5a4123b61
