### ISSUE TITLE
Should this repo be marked as deprecated?

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera-macos-pkg#4]
See warning added to Cantera/cantera-jupyter

**Comment by bryanwweber** [comment]
There's already a note in the README that covers the state of this repo. Are you thinking of something else?

> Note: This repository is in a holding state after the https://github.com/Cantera/cantera/pull/1670 from Cantera. There is a new https://github.com/Cantera/enhancements/issues/177 in progress. When that interface is stable, this repository can be used again to build the Matlab interface for distribution.

**Comment by ischoegl** [comment]
Not sure how I missed that :rofl: ... (apparently anything that lacks some🚨's is lost on me?)
